import type { NextApiRequest, NextApiResponse } from 'next';

type Query = { isCaptured?: string; name?: string; limit?: string };

const pokemon = (req: NextApiRequest, res: NextApiResponse) => {
  const results = getResults(req.query as Query);
  res.status(200).json({ results });
};

const getResults = ({ name, isCaptured, limit = '20' }: Query) =>
  pokemonList
    .filter((pokemon) => {
      const filterName = name ?? pokemon.name;
      const filterIsCaptured =
        typeof isCaptured !== 'undefined'
          ? ['', 'true'].includes(isCaptured)
            ? true
            : false
          : pokemon.isCaptured;
      return (
        pokemon.name.startsWith(filterName) &&
        pokemon.isCaptured === filterIsCaptured
      );
    })
    .slice(0, Number(limit));

const pokemonList = [
  { id: 1, name: 'bulbasaur', isCaptured: false },
  { id: 2, name: 'ivysaur', isCaptured: false },
  { id: 3, name: 'venusaur', isCaptured: false },
  { id: 4, name: 'charmander', isCaptured: true },
  { id: 5, name: 'charmeleon', isCaptured: true },
  { id: 6, name: 'charizard', isCaptured: true },
  { id: 7, name: 'squirtle', isCaptured: false },
  { id: 8, name: 'wartortle', isCaptured: false },
  { id: 9, name: 'blastoise', isCaptured: false },
  { id: 10, name: 'caterpie', isCaptured: true },
  { id: 11, name: 'metapod', isCaptured: true },
  { id: 12, name: 'butterfree', isCaptured: true },
  { id: 13, name: 'weedle', isCaptured: false },
  { id: 14, name: 'kakuna', isCaptured: false },
  { id: 15, name: 'beedrill', isCaptured: false },
  { id: 16, name: 'pidgey', isCaptured: true },
  { id: 17, name: 'pidgeotto', isCaptured: true },
  { id: 18, name: 'pidgeot', isCaptured: false },
  { id: 19, name: 'rattata', isCaptured: true },
  { id: 20, name: 'raticate', isCaptured: false },
  { id: 21, name: 'spearow', isCaptured: true },
  { id: 22, name: 'fearow', isCaptured: false },
  { id: 23, name: 'ekans', isCaptured: false },
  { id: 24, name: 'arbok', isCaptured: false },
  { id: 25, name: 'pikachu', isCaptured: true },
  { id: 26, name: 'raichu', isCaptured: true },
  { id: 27, name: 'sandshrew', isCaptured: false },
  { id: 28, name: 'sandslash', isCaptured: false },
  { id: 29, name: 'nidoran-f', isCaptured: false },
  { id: 30, name: 'nidorina', isCaptured: false },
  { id: 31, name: 'nidoqueen', isCaptured: false },
  { id: 32, name: 'nidoran-m', isCaptured: false },
  { id: 33, name: 'nidorino', isCaptured: false },
  { id: 34, name: 'nidoking', isCaptured: false },
  { id: 35, name: 'clefairy', isCaptured: false },
  { id: 36, name: 'clefable', isCaptured: false },
  { id: 37, name: 'vulpix', isCaptured: true },
  { id: 38, name: 'ninetales', isCaptured: true },
  { id: 39, name: 'jigglypuff', isCaptured: true },
  { id: 40, name: 'wigglytuff', isCaptured: false },
  { id: 41, name: 'zubat', isCaptured: true },
  { id: 42, name: 'golbat', isCaptured: true },
  { id: 43, name: 'oddish', isCaptured: false },
  { id: 44, name: 'gloom', isCaptured: false },
  { id: 45, name: 'vileplume', isCaptured: false },
  { id: 46, name: 'paras', isCaptured: false },
  { id: 47, name: 'parasect', isCaptured: false },
  { id: 48, name: 'venonat', isCaptured: false },
  { id: 49, name: 'venomoth', isCaptured: false },
  { id: 50, name: 'diglett', isCaptured: false },
  { id: 51, name: 'dugtrio', isCaptured: false },
  { id: 52, name: 'meowth', isCaptured: true },
  { id: 53, name: 'persian', isCaptured: true },
  { id: 54, name: 'psyduck', isCaptured: true },
  { id: 55, name: 'golduck', isCaptured: true },
  { id: 56, name: 'mankey', isCaptured: false },
  { id: 57, name: 'primeape', isCaptured: false },
  { id: 58, name: 'growlithe', isCaptured: true },
  { id: 59, name: 'arcanine', isCaptured: true },
  { id: 60, name: 'poliwag', isCaptured: false },
  { id: 61, name: 'poliwhirl', isCaptured: false },
  { id: 62, name: 'poliwrath', isCaptured: false },
  { id: 63, name: 'abra', isCaptured: true },
  { id: 64, name: 'kadabra', isCaptured: true },
  { id: 65, name: 'alakazam', isCaptured: false },
  { id: 66, name: 'machop', isCaptured: false },
  { id: 67, name: 'machoke', isCaptured: false },
  { id: 68, name: 'machamp', isCaptured: false },
  { id: 69, name: 'bellsprout', isCaptured: false },
  { id: 70, name: 'weepinbell', isCaptured: false },
  { id: 71, name: 'victreebel', isCaptured: false },
  { id: 72, name: 'tentacool', isCaptured: true },
  { id: 73, name: 'tentacruel', isCaptured: true },
  { id: 74, name: 'geodude', isCaptured: true },
  { id: 75, name: 'graveler', isCaptured: true },
  { id: 76, name: 'golem', isCaptured: false },
  { id: 77, name: 'ponyta', isCaptured: true },
  { id: 78, name: 'rapidash', isCaptured: true },
  { id: 79, name: 'slowpoke', isCaptured: false },
  { id: 80, name: 'slowbro', isCaptured: false },
  { id: 81, name: 'magnemite', isCaptured: false },
  { id: 82, name: 'magneton', isCaptured: false },
  { id: 83, name: 'farfetchd', isCaptured: false },
  { id: 84, name: 'doduo', isCaptured: false },
  { id: 85, name: 'dodrio', isCaptured: false },
  { id: 86, name: 'seel', isCaptured: false },
  { id: 87, name: 'dewgong', isCaptured: false },
  { id: 88, name: 'grimer', isCaptured: false },
  { id: 89, name: 'muk', isCaptured: false },
  { id: 90, name: 'shellder', isCaptured: false },
  { id: 91, name: 'cloyster', isCaptured: false },
  { id: 92, name: 'gastly', isCaptured: true },
  { id: 93, name: 'haunter', isCaptured: true },
  { id: 94, name: 'gengar', isCaptured: true },
  { id: 95, name: 'onix', isCaptured: false },
  { id: 96, name: 'drowzee', isCaptured: false },
  { id: 97, name: 'hypno', isCaptured: false },
  { id: 98, name: 'krabby', isCaptured: false },
  { id: 99, name: 'kingler', isCaptured: false },
  { id: 100, name: 'voltorb', isCaptured: false },
  { id: 101, name: 'electrode', isCaptured: false },
  { id: 102, name: 'exeggcute', isCaptured: false },
  { id: 103, name: 'exeggutor', isCaptured: false },
  { id: 104, name: 'cubone', isCaptured: false },
  { id: 105, name: 'marowak', isCaptured: false },
  { id: 106, name: 'hitmonlee', isCaptured: false },
  { id: 107, name: 'hitmonchan', isCaptured: false },
  { id: 108, name: 'lickitung', isCaptured: false },
  { id: 109, name: 'koffing', isCaptured: false },
  { id: 110, name: 'weezing', isCaptured: false },
  { id: 111, name: 'rhyhorn', isCaptured: false },
  { id: 112, name: 'rhydon', isCaptured: false },
  { id: 113, name: 'chansey', isCaptured: false },
  { id: 114, name: 'tangela', isCaptured: false },
  { id: 115, name: 'kangaskhan', isCaptured: false },
  { id: 116, name: 'horsea', isCaptured: true },
  { id: 117, name: 'seadra', isCaptured: true },
  { id: 118, name: 'goldeen', isCaptured: false },
  { id: 119, name: 'seaking', isCaptured: false },
  { id: 120, name: 'staryu', isCaptured: true },
  { id: 121, name: 'starmie', isCaptured: false },
  { id: 122, name: 'mr-mime', isCaptured: false },
  { id: 123, name: 'scyther', isCaptured: true },
  { id: 124, name: 'jynx', isCaptured: false },
  { id: 125, name: 'electabuzz', isCaptured: false },
  { id: 126, name: 'magmar', isCaptured: false },
  { id: 127, name: 'pinsir', isCaptured: false },
  { id: 128, name: 'tauros', isCaptured: true },
  { id: 129, name: 'magikarp', isCaptured: true },
  { id: 130, name: 'gyarados', isCaptured: true },
  { id: 131, name: 'lapras', isCaptured: true },
  { id: 132, name: 'ditto', isCaptured: false },
  { id: 133, name: 'eevee', isCaptured: true },
  { id: 134, name: 'vaporeon', isCaptured: false },
  { id: 135, name: 'jolteon', isCaptured: false },
  { id: 136, name: 'flareon', isCaptured: true },
  { id: 137, name: 'porygon', isCaptured: false },
  { id: 138, name: 'omanyte', isCaptured: false },
  { id: 139, name: 'omastar', isCaptured: false },
  { id: 140, name: 'kabuto', isCaptured: true },
  { id: 141, name: 'kabutops', isCaptured: true },
  { id: 142, name: 'aerodactyl', isCaptured: true },
  { id: 143, name: 'snorlax', isCaptured: false },
  { id: 144, name: 'articuno', isCaptured: true },
  { id: 145, name: 'zapdos', isCaptured: false },
  { id: 146, name: 'moltres', isCaptured: false },
  { id: 147, name: 'dratini', isCaptured: true },
  { id: 148, name: 'dragonair', isCaptured: false },
  { id: 149, name: 'dragonite', isCaptured: false },
  { id: 150, name: 'mewtwo', isCaptured: false },
  { id: 151, name: 'mew', isCaptured: false },
];

export default pokemon;
